# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql
#   namespace: devopsexamapp
# spec:
#   clusterIP: None
#   selector:
#     app: mysql
#   ports:
#     - port: 3306
#       targetPort: 3306


# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: mysql
#   namespace: devopsexamapp
# spec:
#   serviceName: "mysql"
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mysql
#   template:
#     metadata:
#       labels:
#         app: mysql
#     spec:
#       initContainers:
#         - name: init-mysql
#           image: busybox
#           command:
#             - sh
#             - -c
#             - |
#               if [ ! -d /var/lib/mysql/mysql ]; then
#                 echo "Initializing: empty data directory";
#               else
#                 echo "MySQL data already exists. Skipping init.";
#                 exit 0
#               fi
#           volumeMounts:
#             - name: mysql-persistent-storage
#               mountPath: /var/lib/mysql
#       containers:
#         - name: mysql
#           image: mysql:5.7
#           ports:
#             - containerPort: 3306
#           env:
#             - name: MYSQL_ROOT_PASSWORD
#               value: "rootpass"
#             - name: MYSQL_DATABASE
#               value: "devops_exam"
#           volumeMounts:
#             - name: mysql-persistent-storage
#               mountPath: /var/lib/mysql
#   volumeClaimTemplates:
#     - metadata:
#         name: mysql-persistent-storage
#       spec:
#         accessModes: ["ReadWriteOnce"]
#         storageClassName: mysql-gp3
#         resources:
#           requests:
#             storage: 1Gi


apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: devopsexamapp
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: devopsexamapp
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
        - name: init-mysql
          image: busybox
          command: ["sh", "-c", "rm -rf /var/lib/mysql/*"]
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpass"
            - name: MYSQL_DATABASE
              value: "devops_exam"
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: mysql-gp3
        resources:
          requests:
            storage: 1Gi

