apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: devopsexamapp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi
