# Flask App Service
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: devopsexamapp
spec:
  selector:
    app: flask
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: devopsexamapp
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
